# [env]
# WINIT_X11_SCALE_FACTOR = "1"
#
[font]
# size = 11
size = 22
normal = { family = "Terminess Nerd Font"}
# bold = { style = "Bold" }
# italic = { style = "Italic" }
# bold_italic = { style = "Bold Italic" }
builtin_box_drawing = true
